samples: "samples.tsv"
units: "units.tsv"

reference:
  dct: ""
  fasta: ""
  loci: ""

mutect2:
  gnomad: ""
  pon: ""

vardict:
  bed: ""

tools:
  common: "docker://marrip/common:1.1.0"
  gatk: "docker://broadinstitute/gatk:4.2.0.0"
  vardict: "docker://marrip/vardict:1.8.2"
