$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  modules:
    type: object
    properties:
      wgs_somatic_pon:
        type: string
    required:
      - wgs_somatic_pon
  reference:
    type: object
    properties:
      dct:
        type: string
      fasta:
        type: string
      intervals:
        type: string
      loci:
        type: string
    required:
      - dct
      - fasta
      - intervals
      - loci
  mutect2:
    type: object
    properties:
      gnomad:
        type: string
      pon:
        type: string
    required:
      - gnomad
      - pon
  vardict:
    type: object
    properties:
      bed:
        type: string
    required:
      - bed
  tools:
    type: object
    properties:
      cnvkit:
        type: string
      common:
        type: string
      gatk:
        type: string
      python:
        type: string
      vardict:
        type: string
  required:
    - samples
    - units
    - modules
    - reference
    - mutect2
    - vardict
    - tools
