$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  reference:
    type: object
    properties:
      fasta:
        type: string
    required:
      - fasta
  mutect2:
    type: object
    properties:
      gnomad:
        type: string
      pon:
        type: string
    required:
      - gnomad
      - pon
  vardict:
    type: object
    properties:
      bed:
        type: string
    required:
      - bed
  tools:
    type: object
    properties:
      common:
        type: string
      gatk:
        type: string
      vardict:
        type: string
  required:
    - samples
    - reference
    - mutect2
    - vardict
    - tools
