samples: "samples.tsv"
units: "units.tsv"

reference:
  dct: "reference/WASH7P.dict"
  fasta: "reference/WASH7P.fna"
  loci: "reference/WASH7P.loci.txt"

mutect2:
  gnomad: "reference/af-only-gnomad.vcf"
  pon: "reference/mutect2_somatic_pon.vcf"

vardict:
  bed: "reference/vardict.bed"

tools:
  common: "docker://marrip/common:1.1.0"
  gatk: "docker://broadinstitute/gatk:4.2.0.0"
  vardict: "docker://marrip/vardict:1.8.2"
